name: Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  kondo:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    env:
      CLJ_KONDO_VERSION: "2023.09.07"
      DOWNLOAD_URL: https://github.com/clj-kondo/clj-kondo/releases/download
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java & Clojure
        uses: ./.github/actions/setup-clojure
        with:
          cache-key: kondo
      - name: Install clj-kondo
        run: |
          curl -OL ${DOWNLOAD_URL}/v${CLJ_KONDO_VERSION}/clj-kondo-${CLJ_KONDO_VERSION}-linux-static-amd64.zip
          curl -OL ${DOWNLOAD_URL}/v${CLJ_KONDO_VERSION}/clj-kondo-${CLJ_KONDO_VERSION}-linux-static-amd64.zip.sha256
          cat clj-kondo-${CLJ_KONDO_VERSION}-linux-static-amd64.zip.sha256 >> SHA256sum.txt
          echo " clj-kondo-${CLJ_KONDO_VERSION}-linux-static-amd64.zip" >> SHA256sum.txt
          sha256sum -c SHA256sum.txt
          unzip -d /usr/local/bin clj-kondo-${CLJ_KONDO_VERSION}-linux-static-amd64.zip
      - run: clj-kondo --version
      - name: Copy Kondo config from deps
        run: >-
          clj-kondo
          --copy-configs
          --dependencies
          --lint "$(clojure -A:dev -Spath)"
          --skip-lint
          --parallel
      - name: Run clj-kondo
        run: >-
          clj-kondo
          --parallel
          --lint src test

  tests:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - name: Setup Java & Clojure
      uses: ./.github/actions/setup-clojure
      with:
        cache-key: tests
    - run: clojure -X:dev:test
      name: Run tests
      env:
        CI: TRUE

  whitespace-linter:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    - name: Setup Java & Clojure
      uses: ./.github/actions/setup-clojure
      with:
        cache-key: whitespace-linter
    - run: clojure -T:whitespace-linter
      name: Run whitespace linter

  check:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    - name: Setup Java & Clojure
      uses: ./.github/actions/setup-clojure
      with:
        cache-key: check
    - run: clojure -M:check
      name: Check namespaces

  codecov:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    - name: Setup Java & Clojure
      uses: ./.github/actions/setup-clojure
      with:
        cache-key: codecov
    - run: clojure -X:dev:test-h2:cloverage
      name: Run tests with Cloverage
    - name: Upload results to codecov.io
      uses: codecov/codecov-action@v3
      with:
        files: ./target/coverage/codecov.json

  codespell:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: codespell-project/actions-codespell@master
